/*
TODO:
- Add configuration and localization support
- Add cooldown option for taunting
- Add option in config for chat commands
- Add option for picking which taunts are allowed?
- Add option to only taunt prop's effect(s)
- Add option to show gibs for props or not
- Add kit configuration for hunters/seekers
- Add team selection and GUI when joining server
- Figure out why Hurt() isn't working for damage passing
- Find a way to bypass "Assertion failed: Stomping old lifeStory" when respawning
- Fix OnPlayerInput checks not allowing players to be props sometimes (dictionary issue)
- Move taunt GUI button to better position
- Unselect active item if selected (make sure to restore fully)
- Update configuration to have usable defaults
- Update configuration automatically
- Whitelist objects to block bad prefabs
- Wipe players inventory when joining props team
*/

using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using Random = UnityEngine.Random;
using Oxide.Game.Rust.Cui;

namespace Oxide.Plugins
{
    [Info("HideAndSeek", "Wulf/lukespragg", 0.1, ResourceId = 1421)]
    [Description("The classic game(mode) of hide and seek, as props.")]

    class HideAndSeek : RustPlugin
    {
        // Do NOT edit this file, instead edit HideAndSeek.json in server/<identity>/oxide/config

        #region Configuration

        string NoPermission => GetConfig("NoPermission", "Sorry, you can't use 'hide' right now");
        string PlayerHiding => GetConfig("PlayerHiding", "<size=20>You're hiding... shhh!</size>");
        string PlayerNotHiding => GetConfig("PlayerNotHiding", "<size=20>You're no longer hiding, run!</size>");

        protected override void LoadDefaultConfig()
        {
            Config["NoPermission"] = NoPermission;
            Config["PlayerHiding"] = PlayerHiding;
            Config["PlayerNotHiding"] = PlayerNotHiding;

            SaveConfig();
        }

        #endregion

        #region General Setup

        readonly Dictionary<BaseEntity, BasePlayer> props = new Dictionary<BaseEntity, BasePlayer>();

        void Loaded()
        {
            LoadDefaultConfig();

            permission.RegisterPermission("hideandseek.allowed", this);
        }

        #endregion

        #region Player Info

        class OnlinePlayer
        {
            public BasePlayer Player;
            public bool IsHidden;
        }

        [OnlinePlayers] Hash<BasePlayer, OnlinePlayer> onlinePlayers = new Hash<BasePlayer, OnlinePlayer>();

        #endregion

        #region Player Restoring

        void OnPlayerInit(BasePlayer player)
        {
            if (!props.ContainsValue(player)) return;

            player.EndSleeping();
            SetPropFlags(player);
        }

        #endregion

        #region Prop Flags

        void SetPropFlags(BasePlayer player)
        {
            // Toggle admin/developer flags to allow third-person
            if (player.net.connection.authLevel > 0) player.SetPlayerFlag(BasePlayer.PlayerFlags.IsAdmin, false);
            if (DeveloperList.IsDeveloper(player)) player.SetPlayerFlag(BasePlayer.PlayerFlags.IsDeveloper, false);

            // Toggle the third-person view
            player.SetPlayerFlag(BasePlayer.PlayerFlags.ThirdPersonViewmode, !player.HasPlayerFlag(BasePlayer.PlayerFlags.ThirdPersonViewmode));

            onlinePlayers[player].IsHidden = !onlinePlayers[player].IsHidden;
        }

        #endregion

        #region Player Hiding

        void HidePlayer(BasePlayer player)
        {
            // Make the player invisible
            player.SetPlayerFlag(BasePlayer.PlayerFlags.Spectating, true);
            player.gameObject.SetLayerRecursive(10);
            player.CancelInvoke("MetabolismUpdate");
            player.CancelInvoke("InventoryUpdate");

            // Set the player flags
            SetPropFlags(player);

            // Show the taunt button
            TauntButton(player, null);

            PrintToChat(player, PlayerHiding);
        }

        void UnhidePlayer(BasePlayer player)
        {
            // Make the player visible
            player.metabolism.Reset();
            player.InvokeRepeating("InventoryUpdate", 1f, 0.1f * Random.Range(0.99f, 1.01f));
            player.SetPlayerFlag(BasePlayer.PlayerFlags.Spectating, false);
            player.gameObject.SetLayerRecursive(17);

            // Set the player flags
            SetPropFlags(player);

            // Remove the taunt button
            CuiHelper.DestroyUi(player, tauntPanel);

            PrintToChat(player, PlayerNotHiding);
        }

        #endregion

        #region Chat Commands

        [ChatCommand("hide")]
        void HideChat(BasePlayer player)
        {
            if (!HasPermission(player, "hideandseek.allowed"))
            {
                SendReply(player, NoPermission);
                return;
            }

            // Check if player is already hidden
            if (player.HasPlayerFlag(BasePlayer.PlayerFlags.Spectating) || onlinePlayers[player].IsHidden) return;

            var ray = new Ray(player.eyes.position, player.eyes.HeadForward());
            var entity = FindObject(ray, 3); // TODO: Make distance (3) configurable
            if (entity == null || props.ContainsKey(entity)) return;

            // Hide active item
            if (player.GetActiveItem() != null)
            {
                var heldEntity = player.GetActiveItem().GetHeldEntity() as HeldEntity;
                //heldEntity?.SetHeld(false);
            }

            // Hide the player
            HidePlayer(player);

            // Create the prop entity
            var propEntity = GameManager.server.CreateEntity(entity.name, player.transform.position, player.transform.rotation);
            propEntity.SendMessage("SetDeployedBy", player, SendMessageOptions.DontRequireReceiver);
            propEntity.SendMessage("InitializeItem", entity, SendMessageOptions.DontRequireReceiver);
            propEntity.Spawn();
            props.Add(propEntity, player);
        }

        [ChatCommand("unhide")]
        void UnhideChat(BasePlayer player)
        {
            if (!HasPermission(player, "hideandseek.allowed"))
            {
                SendReply(player, NoPermission);
                return;
            }

            // Check if player is already unhidden
            if (!player.HasPlayerFlag(BasePlayer.PlayerFlags.Spectating) || !onlinePlayers[player].IsHidden) return;


            // Unhide the player
            UnhidePlayer(player);

            // Remove the prop entity
            if (!props.ContainsValue(player)) return;
            BaseEntity propEntity = null;
            foreach (var prop in props.Where(prop => prop.Value == player)) propEntity = prop.Key;
            if (propEntity == null || propEntity.isDestroyed) return;
            props.Remove(propEntity);
            propEntity.Kill(BaseNetworkable.DestroyMode.Gib);
        }

        #endregion

        #region Prop Taunting

        [ChatCommand("taunt")]
        void TauntPlayer(BasePlayer player)
        {
            // Check if player is already unhidden
            if (!player.HasPlayerFlag(BasePlayer.PlayerFlags.Spectating) || !onlinePlayers[player].IsHidden)
            {
                PrintToChat(player, "You're not a prop!");
                return;
            }

            var r = new System.Random();
            var taunts = new[]
            {
                "animals/bear/attack1",
                "animals/bear/attack2",
                "animals/bear/bite",
                "animals/bear/breathe-1",
                "animals/bear/breathing",
                "animals/bear/death",
                "animals/bear/roar1",
                "animals/bear/roar2",
                "animals/bear/roar3",
                "animals/boar/attack1",
                "animals/boar/attack2",
                "animals/boar/flinch1",
                "animals/boar/flinch2",
                "animals/boar/scream",
                "animals/chicken/attack1",
                "animals/chicken/attack2",
                "animals/chicken/attack3",
                "animals/chicken/cluck1",
                "animals/chicken/cluck2",
                "animals/chicken/cluck3",
                "animals/horse/attack",
                "animals/horse/flinch1",
                "animals/horse/flinch2",
                "animals/horse/heavy_breath",
                "animals/horse/snort",
                "animals/horse/whinny",
                "animals/horse/whinny_large",
                "animals/rabbit/attack1",
                "animals/rabbit/attack2",
                "animals/rabbit/run",
                "animals/rabbit/walk",
                "animals/stag/attack1",
                "animals/stag/attack2",
                "animals/stag/death1",
                "animals/stag/death2",
                "animals/stag/flinch1",
                "animals/stag/scream",
                "animals/wolf/attack1",
                "animals/wolf/attack2",
                "animals/wolf/bark",
                "animals/wolf/breathe",
                "animals/wolf/howl1",
                "animals/wolf/howl2",
                "animals/wolf/run_attack",
                "barricades/damage",
                "beartrap/arm",
                "beartrap/fire",
                "build/frame_place",
                //"build/promote_metal",
                //"build/promote_stone",
                //"build/promote_toptier",
                //"build/promote_wood",
                "build/repair",
                "build/repair_failed",
                "build/repair_full",
                "building/fort_metal_gib",
                "building/metal_sheet_gib",
                "building/stone_gib",
                "building/thatch_gib",
                "building/wood_gib",
                "door/door-metal-impact",
                "door/door-metal-knock",
                "door/door-wood-impact",
                "door/door-wood-knock",
                "door/lock.code.denied",
                "door/lock.code.lock",
                "door/lock.code.unlock",
                "door/lock.code.updated",
                "entities/helicopter/rocket_fire",
                "entities/loot_barrel/gib",
                "entities/loot_barrel/impact",
                "entities/tree/tree-impact",
                "gestures/cameratakescreenshot",
                "gestures/guitarpluck",
                "gestures/guitarstrum",
                "headshot",
                "headshot_2d",
                "hit_notify",
                "item_break",
                "player/beartrap_clothing_rustle",
                "player/beartrap_scream",
                "player/groundfall",
                "player/howl",
                "repairbench/itemrepair",
                "ricochet/ricochet1",
                "ricochet/ricochet2",
                "ricochet/ricochet3",
                "ricochet/ricochet4",
                "weapons/rifle_jingle1",
                "weapons/survey_charge/survey_charge_stick",
                "weapons/vm_machete/attack-1",
                "weapons/vm_machete/attack-2",
                "weapons/vm_machete/attack-3",
                "weapons/vm_machete/deploy",
                "weapons/vm_machete/hit"
            };
            var taunt = taunts[r.Next(taunts.Length)];

            //PrintToChat($"<size=20>{taunt}</size>");
            Effect.server.Run($"assets/bundled/prefabs/fx/{taunt}.prefab", player.transform.position, Vector3.zero);
        }

        #endregion

        #region Damage Passing

        object OnEntityTakeDamage(BaseEntity entity, HitInfo info)
        {
            if (entity is BasePlayer) return null;
            if (!props.ContainsKey(entity))
            {
                var attacker = info.Initiator as BasePlayer;
                attacker?.Hurt(info.damageTypes.Total());
                return true;
            };

            var propPlayer = props[entity];
            if (propPlayer.health <= 1)
            {
                propPlayer.Die();
                return null;
            }
            props[entity].InitializeHealth(propPlayer.health - info.damageTypes.Total(), 100f);

            return true;
        }

        #endregion

        #region Death Handling

        void OnEntityDeath(BaseEntity entity)
        {
            // Check for prop entity/player
            if (!props.ContainsValue(entity.ToPlayer())) return;
            var player = entity.ToPlayer();

            // Get the prop entity
            BaseEntity propEntity = null;
            foreach (var prop in props.Where(prop => prop.Value == player)) propEntity = prop.Key;

            // Unhide and respawn the player
            UnhidePlayer(player);
            props.Remove(player);
            player.RespawnAt(player.transform.position, player.transform.rotation);

            // Remove the prop entity
            if (propEntity && !propEntity.isDestroyed) propEntity.Kill(BaseNetworkable.DestroyMode.Gib);
        }

        void OnEntitySpawned(BaseNetworkable entity)
        {
            // Remove all corpses
            if (entity.name.EndsWith("player_corpse.prefab")) entity.KillMessage();
        }

        #endregion

        #region Spectate Blocking

        object OnRunCommand(ConsoleSystem.Arg arg)
        {
            if (arg?.connection != null && arg.cmd.namefull == "global.spectate") return true;
            return null;
        }

        object OnPlayerInput(BasePlayer player, InputState input)
        {
            if (!props.ContainsValue(player) && !player.IsSpectating() && input.WasJustPressed(BUTTON.FIRE_PRIMARY)) HideChat(player);
            if (props.ContainsValue(player) && player.IsSpectating() && input.WasJustPressed(BUTTON.FIRE_SECONDARY)) UnhideChat(player);
            if (props.ContainsValue(player) && player.IsSpectating() && input.WasJustPressed(BUTTON.JUMP) || input.WasJustPressed(BUTTON.DUCK)) return true;

            return null;
        }

        #endregion

        #region Console Commands

        [ConsoleCommand("global.taunt")]
        void TauntConsole(ConsoleSystem.Arg arg)
        {
            var player = BasePlayer.Find(arg.GetString(0));
            if (player) TauntPlayer(player);
        }

        #endregion

        #region GUI Button

        string tauntPanel;

        void TauntButton(BasePlayer player, string text)
        {
            var elements = new CuiElementContainer();
            tauntPanel = elements.Add(new CuiPanel
            {
                Image = {Color = "0.0 0.0 0.0 0.0"},
                RectTransform = { AnchorMin = "0.026 0.037", AnchorMax = "0.075 0.10" }
            }, "HUD/Overlay", "taunt");
            elements.Add(new CuiElement
            {
                Parent = tauntPanel,
                Components =
                {
                    new CuiRawImageComponent {Url = "http://i.imgur.com/28fdPww.png"},
                    new CuiRectTransformComponent {AnchorMin = "0.0 0.0", AnchorMax = "1.0 1.0"}
                }
            });
            elements.Add(new CuiButton
            {
                Button = {Command = $"taunt {player.userID}", Color = "0.0 0.0 0.0 0.0"},
                RectTransform = {AnchorMin = "0.026 0.037", AnchorMax = "0.075 0.10"},
                Text = {Text = ""}
            });
            CuiHelper.DestroyUi(player, tauntPanel);
            CuiHelper.AddUi(player, elements);
        }

        #endregion

        #region Cleanup Props

        void Unload()
        {
            foreach (var prop in props)
            {
                var propEntity = prop.Key;
                if (!propEntity.isDestroyed) propEntity.Kill(BaseNetworkable.DestroyMode.Gib);
                UnhidePlayer(prop.Value);
            }

            foreach (var player in BasePlayer.activePlayerList) CuiHelper.DestroyUi(player, tauntPanel);
        }

        #endregion

        #region Helper Methods

        T GetConfig<T>(string name, T defaultValue)
        {
            if (Config[name] == null) return defaultValue;
            return (T)Convert.ChangeType(Config[name], typeof(T));
        }

        static BaseEntity FindObject(Ray ray, float distance)
        {
            RaycastHit hit;
            return !Physics.Raycast(ray, out hit, distance) ? null : hit.GetEntity();
        }

        bool HasPermission(BasePlayer player, string perm) => permission.UserHasPermission(player.UserIDString, perm);

        #endregion
    }
}
