/*
TODO:
- Show blocked message via centered GUI overlay
- Move items back to inventory from Research Table
- Add option to remove all deployed Research Tables
- Add option to remove Research Tables in inventory
- Add option to disable crafting of Research Table
- Add permission support to bypass blocks
- Add new hook for when crafting is first started
*/

using System;

namespace Oxide.Plugins
{
    [Info("NoResearch", "Wulf/lukespragg", "0.1.0", ResourceId = 0)]
    [Description("Blocks item researching completely.")]

    class NoResearch : RustPlugin
    {
        // Do NOT edit this file, instead edit NoResearch.json in server/<identity>/oxide/config

        #region Configuration

        string NoResearching => GetConfig("NoResearching", "Researching items is not allowed!");
        string NoResearchTables => GetConfig("NoResearchTables", "Crafting research tables is not allowed!");

        protected override void LoadDefaultConfig()
        {
            Config["NoResearching"] = NoResearching;
            Config["NoResearchTables"] = NoResearchTables;
            SaveConfig();
        }

        #endregion

        #region General Setup

        void Loaded() => LoadDefaultConfig();

        #endregion

        #region Blocking

        object OnItemResearch(Item item, BasePlayer player)
        {
            PrintToChat(player, NoResearching);
            return true;
        }

        #endregion

        #region Helper Methods

        T GetConfig<T>(string name, T defaultValue)
        {
            if (Config[name] == null) return defaultValue;
            return (T)Convert.ChangeType(Config[name], typeof(T));
        }

        #endregion
    }
}
