using System;

namespace Oxide.Plugins
{
    [Info("Announcer", "Wulf/lukespragg", 0.1, ResourceId = 0)]
    [Description("Broadcasts customizable messages when players join/quit.")]

    class Announcer : HurtworldPlugin
    {
        // Do NOT edit this file, instead edit Announcer.json in oxide/config

        #region Configuration

        // Messages
        string PlayerJoined => GetConfig("PlayerJoined", "{name} joined the survivors");
        string PlayerQuit => GetConfig("PlayerQuit", "{name} abandoned the survivors");

        protected override void LoadDefaultConfig()
        {
            // Messages
            Config["PlayerJoined"] = PlayerJoined;
            Config["PlayerQuit"] = PlayerQuit;

            SaveConfig();
        }

        #endregion

        #region Broadcast Messages

        void OnPlayerConnected(PlayerIdentity identity)
        {
            hurtworld.BroadcastChat(PlayerJoined.Replace("{name}", identity.Name));
        }

        void OnPlayerDisconnected(PlayerIdentity identity)
        {
            hurtworld.BroadcastChat(PlayerQuit.Replace("{name}", identity.Name));
        }

        #endregion

        #region Helper Methods

        T GetConfig<T>(string name, T defaultValue)
        {
            if (Config[name] == null) return defaultValue;
            return (T)Convert.ChangeType(Config[name], typeof(T));
        }

        #endregion
    }
}
