using System.Collections.Generic;
using System.Linq;

namespace Oxide.Plugins
{
    [Info("ServerTags", "Wulf/lukespragg", "0.2.1", ResourceId = 764)]
    [Description("Adds specified tags to the existing server tags.")]

    class ServerTags : RustPlugin
    {
        // Do NOT edit this file, instead edit ServerTags.json in server/<identity>/oxide/config

        bool listed;
        IEnumerable<object> Tags  => Config.Get<List<object>>("tags");

        protected override void LoadDefaultConfig()
        {
            Config["tags"] = new List<string> { "arena", "pve" };
        }

        void BuildServerTags(List<string> tags)
        {
            var tagsConfig = Tags;
            tags.AddRange(tagsConfig.Select(tag => tag.ToString()));
            if (!listed) Puts(string.Join(", ", tags.ToArray()));
            listed = true;
        }
    }
}
